backend:
  name: git-gateway
  branch: main # ou la branche principale de votre dépôt

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }